name: Deploy NGINX Deployment to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: harisheks
  NAMESPACE: my-namespace
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

jobs:
  deploy:
    name: Deploy NGINX Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: steebchen/kubectl@v2
        with:
          version: latest
          kubeconfig: ${{ env.KUBE_CONFIG_DATA }}

      - name: Apply deployment.yaml
        run: kubectl apply -f deployment.yml -n ${{ env.NAMESPACE }}
